# GitHub Sponsors and funding options for json2toon

github: [maqboolthoufeeq]

# Uncomment and add your funding platforms as needed:
# patreon: your_patreon_username
# ko_fi: your_kofi_username
custom: ['https://buymeacoffee.com/maqboolthoufeeq']
